apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: worker-trigger
  namespace: serverless-demo
spec:
  broker: broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: worker
